# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
    - step:
        script:
          - apt-get update
          - apt-get -qq install zip
          - zip -r homecast-chat.zip .
          - ls -a
        artifacts: # defining the artifacts to be passed to each future step.
          - homecast-chat.zip
    - step:
        # set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables
        name: Deploy to S3
        deployment: production
        image: atlassian/pipelines-awscli
        script:
         # - aws s3 rm s3://homecast-chat-builds --recursive
          - aws s3 cp homecast-chat.zip s3://homecast-chat-builds/homecast-chat.zip

