version: "3"
networks:
  chat:

services:
  # Launch the Redis used for syncing messages between copies of the client app
  redis:
    image: redis
    networks:
      - chat
    ports:
      - 6379:6379

  # Launch a local version of DynamoDB
  dynamodb-local:
    networks:
      - chat
    build: ./deps/dynamodb-local
    ports:
      - 8000:8000

  # Ephemeral container used for creating the tables in DynamoDB
  dynamodb-tables:
    depends_on:
      - dynamodb-local
    networks:
      - chat
    build: ./deps/dynamodb-tables
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

  # The actual client application
  server1:
    depends_on:
      - redis
      - dynamodb-tables
    networks:
      - chat
    build: ./src
    environment:
      LOCAL: "true"
      ENV_NAME: test
      REDIS_ENDPOINT: redis
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      REGION: eu-west-2
      VERBOSE_REQUEST_LOGGING: 'true'
    ports:
      - 3000:3000
    
  server2:
    depends_on:
      - redis
      - dynamodb-tables
    networks:
      - chat
    build: ./src
    environment:
      LOCAL: "true"
      ENV_NAME: test
      REDIS_ENDPOINT: redis
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      REGION: eu-west-2
      VERBOSE_REQUEST_LOGGING: 'true'
    ports:
      - 3001:3000


